Repository Esri/arcgis-python-api, pull requests merged in 2020-12, with the labels that each got.

#825 multi-task-road-extractor-guide
  guide/14-deep-learning/how-multi-task-road-extractor-works.ipynb
Labels: review in progress

#824 mtre model sample notebook
  samples/04_gis_analysts_data_scientists/automatic_road_extraction_using_deep_learning.ipynb
Labels: review in progress

#845 Added guide for CycleGAN
  guide/14-deep-learning/how-cyclegan-works.ipynb
Labels: changes requested

#842 Added data engineering guides
  guide/16-data-engineering-guides/part1_introduction_to_dataengineering.ipynb
  guide/16-data-engineering-guides/part2_introduction_to_numpy.ipynb
  guide/16-data-engineering-guides/part3_introduction_to_pandas.ipynb
  guide/16-data-engineering-guides/part4_productivity_with_pandas.ipynb
  guide/16-data-engineering-guides/part5_time_series_in_pandas.ipynb
  guide/data/health.json
  guide/data/health.xlsx
  guide/data/sample_cms_data.csv
Labels: changes requested, documentation
