Repository Esri/arcgis-python-api, pull requests merged in 2021-09, with the labels that each got.

#1092 part1_sedf
  guide/05-working-with-the-spatially-enabled-dataframe/part1_introduction_to_sedf.ipynb
Labels: documentation, changes requested

#1080 Added Glacial Terminus extraction notebook
  samples/04_gis_analysts_data_scientists/glacial_terminus_extraction_using_hrnet.ipynb
  static/img/Glacier_tips.gif
Labels: ready for review

#1033 new sequence length section added
  guide/14-deep-learning/dl-on-time-series-data.ipynb
Labels: changes requested
