Repository Esri/arcgis-python-api, pull requests merged in 2021-01, with the labels that each got.

#851 Inference only text models Guide and Sample Notebooks
  guide/14-deep-learning/inference-only-text-models-in-arcgis-learn.ipynb
  samples/04_gis_analysts_data_scientists/translating_story_map_from_one_language_to_another.ipynb
Labels: approved

#865 add change detection guide
  guide/14-deep-learning/how_change_detection_works.ipynb
Labels: approved

#864 adding pix2pix sample notebook
  samples/04_gis_analysts_data_scientists/generating_rgb_imagery_from_digital_surface_model_using_pix2pix.ipynb
Labels: approved

#872 adding guide for dashboard
  guide/13-managing-arcgis-applications/Dashboard.ipynb
Labels: approved

#877 change detection sample
  samples/04_gis_analysts_data_scientists/change_detection_of_buildings_from_satellite_imagery.ipynb
  static/img/change_14_20.gif
Labels: approved

#892 Added guide for retraining windows/doors model
  guide/14-deep-learning/retraining_windows_doors_extraction_model.ipynb
Labels: changes requested

#907 Updated Reconstructing 3D buildings from Aerial LiDAR with Deep Learning
  samples/04_gis_analysts_data_scientists/building_reconstruction_using_mask_rcnn.ipynb
Labels: documentation, enhancement

#871 Unsupervised ML guide
  guide/14-deep-learning/unsupervised-ml-model-guide.ipynb
Labels: approved

#881 Pointrend guide
  guide/14-deep-learning/How_MaskRCNN_works.ipynb
  guide/14-deep-learning/how_deeplabv3_works.ipynb
  guide/14-deep-learning/how_pspnet_works.ipynb
  guide/14-deep-learning/yolov3_object_detector.ipynb
  static/img/pointrend_deeplabv3.jpg
  static/img/pointrend_maskrcnn.jpg
  static/img/pointrend_pspnet.jpg
  static/img/yolov3.jpg
  static/img/yolov3_demo.gif
Labels: changes requested

#897 Adding Faster R-CNN guide
  guide/14-deep-learning/faster-rcnn-object-detector.ipynb
  static/img/fasterrcnn-detections.jpg
  static/img/fasterrcnn.jpg
  static/img/fastrcnn.jpg
  static/img/rcnn.jpg
  static/img/rpn.jpg
Labels: changes requested

#895 Edge detection guide
  guide/14-deep-learning/edge-detection-with-arcgis-learn.ipynb
  static/img/bdcn.jpg
  static/img/edge_detection.jpg
  static/img/hed.jpg
Labels: changes requested

#876 adds image captioning guide
  guide/14-deep-learning/how_image_captioning_works.ipynb
Labels: changes requested

#868 adding edge_detection_sample_notebook
  samples/04_gis_analysts_data_scientists/land_parcel_extraction_using_edge_detection_deep_learning_model.ipynb
Labels: approved

#869 Adding SequenceToSequence guide
  guide/14-deep-learning/data/address_standardization_correction_data/LICENSE.txt
  guide/14-deep-learning/how-sequencetosequence-works.ipynb
Labels: changes requested

#870 Adding SequenceToSequence sample(address-standardization-and-correction)
  samples/04_gis_analysts_data_scientists/address-standardization-and-correction-with-sequencetosequence.ipynb
  samples/04_gis_analysts_data_scientists/data/address_standardization_correction_data/LICENSE.txt
Labels: changes requested

#902 Initial release notes for 1.8.4
  guide/02-api-overview/release-notes.ipynb
Labels: documentation
