Repository Esri/arcgis-python-api, pull requests merged in 2021-07, with the labels that each got.

#1026 ArcGIS API for Python 1.9.0 release notes
  guide/02-api-overview/release-notes.ipynb
Labels: documentation

#1031 Doccano updated implementation
  guide/14-deep-learning/labeling-text-using-doccano.ipynb
  misc/tools/doccano_deployment/README.md
  misc/tools/doccano_deployment/annotation.html
  misc/tools/doccano_deployment/elevated_prompt_check.ps1
  misc/tools/doccano_deployment/get_username.ps1
  misc/tools/doccano_deployment/getpwd.ps1
  misc/tools/doccano_deployment/install.bat
  misc/tools/doccano_deployment/install_deps.ps1
  misc/tools/doccano_deployment/refresh_path.bat
  misc/tools/doccano_deployment/reports_label.jsonl
  misc/tools/doccano_deployment/run_doccano.bat
  misc/tools/doccano_deployment/start_webpack.bat
  misc/tools/doccano_deployment/uninstall.bat
  misc/tools/doccano_deployment/uninstall.ps1
Labels: to be reviewed

#1061 updates to pointCNN guide - due to new features and workflow changes.
  guide/14-deep-learning/point_cloud_segmentation_using_pointcnn.ipynb
Labels: review in progress

#975 unsupervised ml model sample notebook
  samples/04_gis_analysts_data_scientists/detecting-deforestation-using-kmeans-clustering-on-sentinel-imagery.ipynb
Labels: approved
