Repository Esri/arcgis-python-api, pull requests merged in 2021-08, with the labels that each got.

#1067 updated install and setup guide
  guide/01-getting-started/install-and-set-up.ipynb
Labels: approved

#772 Animal species identification NB
  samples/04_gis_analysts_data_scientists/wildlife_species_identification_in_camera_trap_images.ipynb
Labels: ready for review

#1066 Added MMSegmentation guide
  guide/14-deep-learning/using-mmsegmentation-with-arcgis-learn.ipynb
  static/img/Landcover_gif.gif
Labels: ready for review

#1062 updates to MTRE guide, with latest changes till 1.9.0.
  guide/01-getting-started/install-and-set-up.ipynb
  guide/14-deep-learning/how-multi-task-road-extractor-works.ipynb
  guide/14-deep-learning/point_cloud_segmentation_using_pointcnn.ipynb
Labels: review in progress
