Repository Esri/arcgis-python-api, pull requests merged in 2021-03, with the labels that each got.

#948 multi-gpu-training-guide
  guide/14-deep-learning/utilize_multiple_gpus_to_train_model.ipynb
Labels: changes requested

#949 remove try it live from non-working nbs
  items_metadata.yaml
Labels: DO NOT MERGE

#946 updated two samples for try it live
  samples/04_gis_analysts_data_scientists/analyzing_growth_factors_of_airbnb_properties_in_new_york_city.ipynb
  samples/04_gis_analysts_data_scientists/how-much-green-is-Delhi-as-on-15-oct-2017.ipynb
Labels: approved

#937 initial version of 1.8.5 release notes
  guide/02-api-overview/release-notes.ipynb
Labels: documentation
