Repository Esri/arcgis-python-api, pull requests merged in 2022-01, with the labels that each got.

#1082 add branch version parcel fabric samples
  guide/04-feature-data-and-analysis/part1_parcel_fabric_an_introduction.ipynb
  guide/04-feature-data-and-analysis/part2_branch_versioning_with_parcel_fabrics.ipynb
  guide/04-feature-data-and-analysis/part3_create_a_parcel_record.ipynb
  guide/04-feature-data-and-analysis/part4_query_parcels.ipynb
  guide/04-feature-data-and-analysis/part5_merge_parcels.ipynb
Labels: approved

#1125 SeDF Guides: part 2 and 3
  guide/05-working-with-the-spatially-enabled-dataframe/part2_data_io_reading_data.ipynb
  guide/05-working-with-the-spatially-enabled-dataframe/part3_data_io_writing_data.ipynb
Labels: approved

#1133 Adds Mussel Farm Detection using MMDetection sample notebook
  samples/04_gis_analysts_data_scientists/detecting_mussel_farms_using_deep_learning.ipynb
Labels: changes requested

#1134 Admin sample - Inventory portal items
  samples/03_org_administrators/inventory-organizational-content.ipynb
Labels: changes requested

#1157 Release notes for 2.0.0
  guide/02-api-overview/release-notes.ipynb
Labels: documentation

#1158 Full release notes for Version 2.0.0
  guide/02-api-overview/release-notes.ipynb
Labels: documentation
