Repository Esri/arcgis-python-api, pull requests merged in 2022-08, with the labels that each got.

#1275 Land Surface Temperature prediction from multispectral imagery using Pix2Pix
  samples/04_gis_analysts_data_scientists/generating_lst_from_multispectral_imagery_using_pix2pix.ipynb
Labels: to be reviewed

#1321 remove references to DependencyManager from release notes
  guide/02-api-overview/release_notes_201.ipynb
Labels: documentation

#1326 rename notebooks to account for Gatsby redirect requirements
  samples/02_power_users_developers/using_geoprocessing_tools_rn.ipynb
  samples/03_org_administrators/batch_creation_of_groups_rn.ipynb
  samples/03_org_administrators/clone_portal_users_groups_and_content_rn.ipynb
  samples/04_gis_analysts_data_scientists/chennai_floods_analysis_rn.ipynb
Labels: documentation

#1303 correct the hyperlink for Typing
  guide/02-api-overview/release_notes_201.ipynb
Labels: documentation, to be reviewed

#1334 Syncing next with master with recent pull request
  guide/02-api-overview/release_notes_201.ipynb
Labels: documentation

#1333 Added google colab instructions to install and setup guide
  guide/01-getting-started/install-and-set-up.ipynb
Labels: approved
