Repository Esri/arcgis-python-api, pull requests merged in 2022-05, with the labels that each got.

#1187 SAR to RGB using CycleGAN notebook updated
  samples/04_gis_analysts_data_scientists/sar_to_rgb_image_translation_using_cyclegan.ipynb
  static/img/sar_to_rgb_results.gif
Labels: to be reviewed

#1243 NER port prepare_data to prepare_textdata
  guide/14-deep-learning/how-named-entity-recognition-works.ipynb
Labels: review in progress

#1260 add initial release notes for 2.0.1 current through 3.28.22
  guide/02-api-overview/release_notes_201.ipynb
Labels: documentation
