Repository Esri/arcgis-python-api, pull requests merged in 2023-01, with the labels that each got.

#1214 oriented imagery sample notebook
  samples/04_gis_analysts_data_scientists/traffic-light-detection-on-oriented-imagery.ipynb
  static/img/oriented_image_yolo_output.gif
Labels: changes requested, ready for review

#1403 adding PSETAE guide
  guide/14-deep-learning/how_PSETAE_works.ipynb
Labels: approved

#1418 Update markdown headings to align with gatsby building
  samples/05_content_publishers/publish_ogc_services.ipynb
Labels: documentation

#1420 Update toc and markdown cells structures
  samples/04_gis_analysts_data_scientists/tonga_volcano_eruption_2022.ipynb
Labels: documentation

#1414 Release notes for 2.1
  guide/02-api-overview/release_notes_210.ipynb
Labels: documentation

#1428 remove extra markdown heading
  samples/04_gis_analysts_data_scientists/coastline_extraction-usa-landsat8_multispectral_imagery.ipynb
Labels: documentation

#1432 Fix broken relative link formats
  guide/01-getting-started/understanding-conda.ipynb
  guide/02-api-overview/overview-of-the-arcgis-api-for-python.ipynb
  guide/02-api-overview/release_notes_210.ipynb
Labels: documentation

#1434 Correct module names and alter table of contents for install guide
  guide/01-getting-started/install-and-set-up.ipynb
Labels: documentation

#1436 Fix rendering of the `Performing big data analysis` guide for body and right-hand navigation
  guide/07-working-with-bigdata/03-performing_big_data_analysis.ipynb
Labels: documentation

#1437 Remove methods from `RasterCollection` class that won't be added until next release
  guide/02-api-overview/release_notes_210.ipynb
Labels: documentation
