Repository Esri/arcgis-python-api, pull requests merged in 2023-09, with the labels that each got.

#1633 Fixed and enhanced the guide `accessing-and-managing-groups.ipynb`
  guide/03-the-gis/accessing-and-managing-groups.ipynb
Labels: enhancement, documentation, ready for review

#1635 adding hub intro guide again on new branch
  guide/13-managing-arcgis-applications/hub-submodule-intro.ipynb
Labels: documentation, approved

#1451 hub and sites sample notebook
  guide/13-managing-arcgis-applications/introduction_to_hub_initiatives_and_sites.ipynb
Labels: documentation, approved

#1665 Update supported versions of Python
  guide/01-getting-started/system-requirements.ipynb
Labels: documentation

#1662 new branch for the pop exploration dashboard sample
  samples/02_power_users_developers/population_exploration_dashboard.ipynb
Labels: documentation

#1677 fix typo in import statement
  guide/01-getting-started/install-and-set-up.ipynb
Labels: documentation
