Repository Esri/arcgis-python-api, pull requests merged in 2023-06, with the labels that each got.

#1431 Added Panoptic Segmentation guide
  guide/14-deep-learning/panoptic_segmentation_with_maxdeeplab.ipynb
Labels: changes requested

#1570 How AutoDL works guide enhancements
  guide/14-deep-learning/how_AutoDL_works.ipynb
Labels: to be reviewed

#1592 Update collaboration guide to switch the host organization
  guide/03-the-gis/building-distributed-gis-through-collaborations.ipynb
Labels: documentation
