Repository Esri/arcgis-python-api, pull requests merged in 2024-11, with the labels that each got.

#2136 Update OGC Sample
  samples/05_content_publishers/publish_ogc_services.ipynb
Labels: documentation

#2144 Update for how much green sample
  samples/04_gis_analysts_data_scientists/how-much-green-is-Delhi-as-on-21-oct-2022.ipynb
Labels: documentation, update_24

#2163 changes to reflect new map widget
  samples/04_gis_analysts_data_scientists/drive_time_analysis_for_opioid_epidemic.ipynb
Labels: update_24

#2137 Update features edit sample
  samples/05_content_publishers/updating_features_in_a_feature_layer.ipynb
Labels: documentation
