Repository Esri/arcgis-python-api, pull requests merged in 2024-07, with the labels that each got.

#1831 sample notebook `Publishing web maps and web scenes` resolved
  samples/05_content_publishers/publishing_web_maps_and_web_scenes.ipynb
Labels: ready for review

#1747 fixed `visualize_monthly_changes_in_hirakund_reservoir_using_video.ipynb`
  samples/04_gis_analysts_data_scientists/visualize_monthly_changes_in_hirakund_reservoir_using_video.ipynb
Labels: fixed, changes requested, ready for review

#1821 fixed Identify Items That Use Insecure URLs sample notebook
  samples/05_content_publishers/Identify_Items_That_Use_Insecure_URLs.ipynb
Labels: ready for review

#1744 `analyzing_growth_factors_of_airbnb_properties_in_new_york_city.ipynb` sample notebook now running and fixed
  samples/04_gis_analysts_data_scientists/analyzing_growth_factors_of_airbnb_properties_in_new_york_city.ipynb
Labels: fixed, ready for review

#1738 resolves issue#9773, fixed `using_and_updating_GIS_content.ipynb`
  samples/05_content_publishers/using_and_updating_GIS_content.ipynb
Labels: fixed, ready for review

#1874 Add deprecation notice for the geoanalytics module
  guide/07-working-with-bigdata/01-introduction.ipynb
Labels: documentation

#1875 Update system requirements text for 2.3.1 release
  guide/01-getting-started/system-requirements.ipynb
Labels: documentation
