Repository Esri/arcgis-python-api, pull requests merged in 2024-09, with the labels that each got.

#1959 Clone_Groups sample
  samples/03_org_administrators/clone_a_group.ipynb
Labels: documentation, update_24

#1998 add note about remove samples based on archived repo
  samples/02_power_users_developers/building_a_change_detection_app_using_jupyter_dashboard.ipynb
  samples/02_power_users_developers/jupyter_dashboard_for_raster_analytics.ipynb
  samples/02_power_users_developers/population_exploration_dashboard.ipynb
Labels: documentation

#1957 Geoprocessing sample rework
  samples/02_power_users_developers/using_geocoding_geometry.ipynb
  samples/02_power_users_developers/using_geoprocessing_tools_rn.ipynb
Labels: documentation, update_24

#1945 04/appending-features
  guide/04-feature-data-and-analysis/appending-features.ipynb
Labels: documentation, update_24

#1952 13/cloning-complex-apps
  guide/13-managing-arcgis-applications/cloning-complex-apps.ipynb
Labels: documentation, update_24

#1942 updates for spatial_filters guide
  guide/15-working-with-geometries/part4_spatial_filters.ipynb
Labels: documentation, update_24

#1939 Update the Introduction of Tutorials section of the Maps guides for 2.4
  guide/10-mapping-and-visualization/part1_introduction_to_using_the_map_widget.ipynb
Labels: documentation, update_24

#1937 13/experience-builder-workflows
  guide/13-managing-arcgis-applications/experience-builder-workflows.ipynb
Labels: documentation, update_24

#1933 what is geocoding guide fixed
  guide/09-finding-places-with-geocoding/part1_what_is_geocoding.ipynb
Labels: ready for review, update_24

#1930 Update the Managing offline map areas guide for 2.4
  guide/10-mapping-and-visualization/managing-offline-map-areas.ipynb
Labels: documentation, update_24

#1926 Fix mapping for reverse geocode
  guide/09-finding-places-with-geocoding/part5_reverse_geocoding.ipynb
  guide/09-finding-places-with-geocoding/part6_working_with_custom_geocoders.ipynb
Labels: documentation, update_24

#1924 Minor changes to features guides
  guide/04-feature-data-and-analysis/discovering-suitable-locations-in-feature-data.ipynb
  guide/04-feature-data-and-analysis/part4_query_parcels.ipynb
  guide/04-feature-data-and-analysis/part5_merge_parcels.ipynb
  guide/04-feature-data-and-analysis/performing-proximity-analysis-on-feature-data.ipynb
  guide/04-feature-data-and-analysis/summarizing-feature-data.ipynb
Labels: documentation, update_24

#1919 The gis guides
  guide/03-the-gis/accessing-and-creating-content.ipynb
  guide/03-the-gis/accessing-and-managing-groups.ipynb
Labels: documentation, update_24

#2016 update markdown headings for correct navigation
  guide/14-deep-learning/add_custom_nlp_models_using_model_extension.ipynb
Labels: documentation

#2023 Update mussel farms notebook (map-widget)
  samples/04_gis_analysts_data_scientists/detecting_mussel_farms_using_deep_learning.ipynb
Labels: learn, update_24

#1958 Remove guides using the jupyter_dashboards package
  samples/02_power_users_developers/building_a_change_detection_app_using_jupyter_dashboard.ipynb
  samples/02_power_users_developers/jupyter_dashboard_for_raster_analytics.ipynb
  samples/02_power_users_developers/population_exploration_dashboard.ipynb
Labels: documentation, update_24

#1956 Remove using geometry functions sample
  samples/02_power_users_developers/using_geometry_functions.ipynb
Labels: documentation, update_24

#1918 SEDF Visualization Notebook
  guide/05-working-with-the-spatially-enabled-dataframe/spatially-enabled-dataframe-advanced-topics.ipynb
  guide/05-working-with-the-spatially-enabled-dataframe/visualizing-data-with-the-spatially-enabled-dataframe.ipynb
Labels: documentation, update_24

#1902 Remove the spatial and temporal gax distribution sample
  samples/04_gis_analysts_data_scientists/spatial_and_temporal_trends_of_service_calls.ipynb
Labels: documentation, update_24

#1917 Working with SeDF guide update
  guide/05-working-with-the-spatially-enabled-dataframe/spatially-enabled-dataframe-advanced-topics.ipynb
Labels: documentation, update_24

#1916 Remove zoom level from the map instantiation
  guide/05-working-with-the-spatially-enabled-dataframe/introduction-to-the-spatially-enabled-dataframe.ipynb
  guide/05-working-with-the-spatially-enabled-dataframe/part1_introduction_to_sedf.ipynb
  guide/16-introduction-to-data-engineering-in-python/part1_introduction_to_dataengineering.ipynb
Labels: documentation, update_24

#1915 Update guide: Remove use of onclick
  guide/08-using-geoprocessing-tools/using-geoprocessing-tools.ipynb
Labels: documentation, update_24

#1913 Geoenrich part 1 updates
  guide/12-enrich-data-with-thematic-information/part2_where_to_enrich_study_areas.ipynb
Labels: documentation, update_24

#1912 Second part of Geoenrichment changes
  guide/12-enrich-data-with-thematic-information/part3_where_to_enrich_named_stat_areas.ipynb
  guide/12-enrich-data-with-thematic-information/part4_what_to_enrich_datacollections_analysisvariables.ipynb
Labels: documentation, update_24

#1905 Update 15/part1_introduction_what_is_geometry.ipynb
  guide/15-working-with-geometries/part1_introduction_what_is_geometry.ipynb
Labels: documentation, update_24

#1904 Updates to 04/editing-features and 04/checking-out-data-from-feature-layers-using-replicas
  guide/04-feature-data-and-analysis/checking-out-data-from-feature-layers-using-replicas.ipynb
  guide/04-feature-data-and-analysis/editing-features.ipynb
Labels: documentation, update_24

#1900 Update smart mapping guide
  guide/10-mapping-and-visualization/smart-mapping.ipynb
Labels: documentation, update_24

#2073 2.4.0 changes - removal of 2 sections, added 1
  guide/10-mapping-and-visualization/part5_saving_updating_and_embedding_map_widget.ipynb
Labels: update_24
