Repository Esri/arcgis-python-api, pull requests merged in 2024-01, with the labels that each got.

#1637 Update raster data and notebook
  samples/04_gis_analysts_data_scientists/creating_raster_information_product_using_raster_analytics.ipynb
Labels: ready for review

#1751 remove sr3 guide because of image problem
  guide/14-deep-learning/how_sr3_works.ipynb
Labels: documentation

#1753 Explore sr3 guide
  guide/14-deep-learning/how_sr3_works.ipynb
Labels: documentation

#1723 `discovering-suitable-locations-in-feature-data.ipynb` guide now working
  guide/04-feature-data-and-analysis/discovering-suitable-locations-in-feature-data.ipynb
Labels: fixed, to be reviewed, ready for review

#1714 `overwriting_feature_layers.ipynb` corrected and enhanced
  samples/05_content_publishers/overwriting_feature_layers.ipynb
Labels: enhancement, fixed, ready for review
