Repository Esri/arcgis-python-api, pull requests merged in 2025-04, with the labels that each got.

#2131 sample notebook `visualize_monthly_changes_in_hirakund_reservoir_using_video.ipynb` updated according to map widget 2.4.0
  samples/04_gis_analysts_data_scientists/visualize_monthly_changes_in_hirakund_reservoir_using_video.ipynb
Labels: enhancement, ready for review, update_24, Sample Notebook

#2132 Sample Overwrite FL
  samples/05_content_publishers/overwriting_feature_layers.ipynb
Labels: documentation

#2160 `Using and updating GIS content` sample notebook revamped according to the new map widget
  samples/05_content_publishers/using_and_updating_GIS_content.ipynb
Labels: enhancement, ready for review, update_24, Sample Notebook

#2133 Update table to pdf
  samples/05_content_publishers/pdf_table_to_pdf_map.ipynb
Labels: documentation

#2178 changes to reflect new map widget changes and Folder.add() for raster sample
  samples/04_gis_analysts_data_scientists/determining_site_suitability_for_oil_palm_plantation.ipynb
Labels: update_24
